### ISSUE TITLE
MyIPConnector wanted

### ISSUE THREAD

**Issue by jhdscript** [guille/RaftCore#10]
Hello,

could you provide me a sample for MyIPConnector please.

Regards

**Comment by guille** [comment]
I do not have any implementations of it. It's just some pseudocode from the README to make an example of an user-defined connection. It would probably be relatively similar to [APIRaftConnector.cs](https://github.com/guille/RaftCore/blob/master/RaftCore/Connections/Implementations/APIRaftConnector.cs)

**Comment by jhdscript** [comment]
Sorry to disturb you again but have you an example for a tcpconnector ?
