### ISSUE TITLE
Add vote codition

### ISSUE THREAD

**Issue by xyz0822** [guille/RaftCore#8]
in RequestVote method,should we compare with term > CurrentTerm  and vote true?
```
if(term>CurrentTerm)
 voteGranted = true;
```

**Comment by guille** [comment]
I don't think so. It's been a while, but I just opened the [Raft paper](https://raft.github.io/raft.pdf) to check and I think your proposed change doesn't correctly follow the algorithm.

You can refer to Figure 2 in the paper for a summary of the RequestVote receiver implementation, or read §5.2 for more context.
